### ISSUE TITLE
Suggestion to use a more liberal License

### ISSUE THREAD

**Issue by hmalphettes** [Stephn-R/Electron-Boilerplate#4]
Hi there and thanks for providing this skeleton publicly.
In my understanding it is intended as a starting point or as example code.
Unfortunately I cannot use it in my projects as it is licensed with GPL and my projects are either MIT/BSD or proprietary.

Would you consider adopting a different license?

Thanks for your attention!

**Comment by stephnr** [comment]
Done :smile: Feel free to use it and don't forget to star the repo!

**Comment by hmalphettes** [comment]
Thanks!
